export const VALIDATION_COLUMN_ORDER_BY_SECTION: Record<string, string[]> = {
  "LLDP Errors": [
    "Device A Rack",
    "Device A Name",
    "Device A Port",
    "Device B Rack",
    "Device B Name",
    "Device B Port",
    "Expected Device B Rack",
    "Expected Device B Name",
    "Expected Device B Port",
    "LLDP Status",
    "patchPanelMatrix",
  ],
  "Optic Errors": [
    "Device Name",
    "Device Port",
    "Source Device Name",
    "Source Device Port",
    "Remote Device Name",
    "Remote Device Port",
    "Tx Power",
    "Rx Power",
    "patchPanelMatrix",
  ],
  "Interface Errors": [
    "Device Name",
    "Device Port",
    "Source Device Name",
    "Source Device Port",
    "Remote Device Name",
    "Remote Device Port",
    "Issue",
    "patchPanelMatrix",
  ],
  "FEC_BER Errors": [
    "Device Rack",
    "Device Name",
    "Device Port",
    "PRE_FEC_BER",
    "Lock Status",
    "Remote Device",
    "Remote Interface",
    "Error Message",
    "patchPanelMatrix",
  ],
  "Fan Errors": [
    "Device Name",
    "Fan Name",
    "Fan Slot",
    "Status",
    "Error Message",
  ],
};
